### Sujal Vivek Choudhari -  Python Programming Experiment 2
60003220216 IT3 (2) 

**Lists, Tuples, Dict and Numpy**


### Q1. Select Random from Lists

In [2]:
mylist = [2,4,6,8,10]

In [3]:
import random

In [4]:
random.choice(mylist)

4

### Q2:. Write a Python program to count the elements in a list until an element is a tuple

In [5]:
myotherlist = ["1",2,3,4,5,(2,3,4,"tuple"),"notuple"]

In [6]:
count =0
for item in myotherlist:
    if not isinstance(item,tuple):
        count += 1
    else:
        break

count

5

### Q3: Create a dictionary of 5 countries with their currency details and display them

In [7]:
country = {
    "India": "INR",
    "USA": "USD",
    "CANADA": "Canadian $",
    "JAPAN":"Yen",
    "Europe": "Euro"
}

for k,v in country.items():
    print(f"{v} is the currency of {k}")

INR is the currency of India
USD is the currency of USA
Canadian $ is the currency of CANADA
Yen is the currency of JAPAN
Euro is the currency of Europe


### Q4: Write a Python program to reverse a tuple

In [8]:
mytuple = ("Hello", "World", "Is", "This")

In [9]:
converted_list = list(mytuple)
converted_list.reverse()
new_tuple = tuple(converted_list)
new_tuple

('This', 'Is', 'World', 'Hello')

## Numpy Questions

### Q5: Create a Numpy array filled with all ones

In [10]:
import numpy as np

In [11]:
all_one = np.empty(10,dtype=int)
all_one.fill(1)
all_one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Q6: Check whether a Numpy array contains a specified row

In [12]:
multi_array = np.array([[1,2,3],[3,4,5],[5,6,7]])
specified_row = [1,2,3]
# specified_row = [1,2,4]

In [13]:
if specified_row in multi_array.tolist():
    print("Yup")
else: print("Nope")

Yup


### Q7: Compute mathematical operations on Array, Add & Multiply two matrices

In [14]:
m1 = np.array([[2,0],[0,2]],dtype=float)
m2 = np.array([[5,3],[10,34]],dtype=float)

In [15]:
m3 = m1 * m2
m4 = m1 + m2
print(f"Multiplication is\n {m3}")
print(f"\n\nAddition is\n {m4}")

Multiplication is
 [[10.  0.]
 [ 0. 68.]]


Addition is
 [[ 7.  3.]
 [10. 36.]]


### Q8: Find the most frequent value in a NumPy array

In [16]:
np_array = np.array([2,3,4,5,6,66,6,6,6,6,6,6,6,6,6,6,6,6,6,6,4,4,4,4,2,2,2,2,0,2,3,4,5,5,1])
np.bincount(np_array).argmax()

6

### Q9: Flatten a 2d numpy array into ld array

In [17]:
np_arr = np.array([[2,3,4,6],[2,3,4,6]])
np_arr.flatten()

array([2, 3, 4, 6, 2, 3, 4, 6])

### Q10:  Calculate the sum of all columns in a 2D NumPy array

In [18]:
def colsum(arr, n, m):
    for i in range(n):
        su = 0;
        for j in range(m):
            su += arr[j][i]
        print(su, end = " ")    
 
TwoDList = [[1, 2, 3], [4, 5, 6], 
            [7, 8, 9], [10, 11, 12]]
TwoDArray = np.array(TwoDList)
 
print(TwoDArray)
 
colsum(TwoDArray, len(TwoDArray[0]), len(TwoDArray))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
22 26 30 

### Q11: Calculate the average, variance and standard deviation in Python using NumPy

In [19]:
arr = np.array([2,3,4,5,6,7,7,7,6,54,4,34])

np.average(arr),np.var(arr),np.std(arr)

(11.583333333333334, 229.24305555555551, 15.140774602230744)

### Q12: Insert a space between characters of all the elements of a given NumPy array?

In [20]:
arr = np.array(['a','b','c'])

" ".join(arr.tolist())

'a b c'

### Q13: Sort matrix in Numpy

In [22]:
martix = np.array([[3,2,1],[4,5,6],[7,8,9]],dtype=int)

In [25]:
martix.sort()
martix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])